### ISSUE TITLE
native error

### ISSUE THREAD

**Issue by xgaxpp** [micronaut-projects/micronaut-netflix#63]
### Task List

- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

After the introduction of Netflix related packages, native cannot compile normally

**error**

Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.ClassLoader.defineClass1(ClassLoader, String, byte[], int, int, ProtectionDomain, String) is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Detailed message:
Trace:
        at parsing java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
Call path from entry point to java.lang.ClassLoader.defineClass(String, byte[], int, int, ProtectionDomain):
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1015)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:878)
        at com.oracle.svm.reflect.ClassLoader_defineClass_c6c343b4d6dc22ca64eb2d8503b13ac9c340dcb3_4471.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:566)
        at javax.xml.transform.TransformerException.printStackTrace(TransformerException.java:345)
        at javax.xml.transform.TransformerException.printStackTrace(TransformerException.java:285)
        at com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:768)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)

Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1

**build.gradle**

plugins {
    id "com.github.johnrengelman.shadow"
    id "io.micronaut.application"
    id 'io.franzbecker.gradle-lombok'
}

version "0.1"
group "com.ish.goods"

ext {
    netflixVersion = "2.0.0"
}
micronaut {
    runtime "netty"
    testRuntime "junit5"
    processing {
        incremental true
        annotations "com.ish.goods.*"
    }
}

dependencies {
    // lombok
    annotationProcessor "org.projectlombok:lombok"
    // micronaut
    implementation("io.micronaut:micronaut-validation")
    implementation("io.micronaut:micronaut-runtime")
    implementation("io.micronaut.rxjava3:micronaut-rxjava3")
    implementation("io.micronaut.rxjava3:micronaut-rxjava3-http-client:1.0.0")
    implementation("io.micronaut.data:micronaut-data-hibernate-jpa")
    implementation("io.micronaut:micronaut-discovery-client")
    // tracing
    implementation("io.micronaut:micronaut-tracing")
    implementation("io.opentracing.brave:brave-opentracing")
    runtimeOnly("io.zipkin.brave:brave-instrumentation-http")
    runtimeOnly("io.zipkin.reporter2:zipkin-reporter")

    // netflix
    implementation("io.micronaut.netflix:micronaut-netflix-hystrix")
    implementation("io.micronaut.netflix:micronaut-netflix-ribbon")

    // common
    implementation 'cn.hutool:hutool-all:5.4.7'
    implementation('mysql:mysql-connector-java:8.0.21')
    // jar
    implementation fileTree( dir: 'lib', includes: ['*jar'])
    implementation project(":ish-common")
    // runtime
    runtimeOnly("io.micronaut.sql:micronaut-jdbc-hikari")
    runtimeOnly("ch.qos.logback:logback-classic")
}

mainClassName = "com.ish.goods.GoodsApplication"

java {
    sourceCompatibility = JavaVersion.toVersion('11')
    targetCompatibility = JavaVersion.toVersion('11')
}

**Comment by ilopmar** [comment]
@xgaxpp can you please create a sample application that only has the netflix libraries? In your example you have lombok, zipkin, jpa, rxjava3,...

**Comment by xgaxpp** [comment]
@ilopmar hi this is sample uri https://github.com/xgaxpp/netflix-sample.git

This is the complete error message:

➜  sample ./gradlew nativeImage

> Task :nativeImage
[application:20459]    classlist:   5,000.51 ms,  0.96 GB
[application:20459]        (cap):   4,267.36 ms,  0.96 GB
[application:20459]        setup:   5,684.40 ms,  0.96 GB
[application:20459]     (clinit):     737.95 ms,  5.31 GB
[application:20459]   (typeflow):  20,509.94 ms,  5.31 GB
[application:20459]    (objects):  22,860.33 ms,  5.31 GB
[application:20459]   (features):   3,890.88 ms,  5.31 GB
[application:20459]     analysis:  50,080.26 ms,  5.31 GB
Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.ClassLoader.defineClass1(ClassLoader, String, byte[], int, int, ProtectionDomain, String) is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Detailed message:
Trace:
        at parsing java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
Call path from entry point to java.lang.ClassLoader.defineClass(String, byte[], int, int, ProtectionDomain):
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1015)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:878)
        at com.oracle.svm.reflect.ClassLoader_defineClass_c6c343b4d6dc22ca64eb2d8503b13ac9c340dcb3_1704.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:566)
        at com.oracle.svm.core.hub.DynamicHub.initEnumConstantsAtRuntime(DynamicHub.java:477)
        at com.oracle.svm.core.hub.DynamicHub.lambda$initEnumConstantsAtRuntime$1(DynamicHub.java:457)
        at com.oracle.svm.core.hub.DynamicHub$$Lambda$1817/0x00000007c1b2a440.get(Unknown Source)
        at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:190)
        at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:143)
        at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:331)
        at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VARARGS:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)

Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1

> Task :nativeImage FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':nativeImage'.
> Process 'command 'native-image'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 5s
3 actionable tasks: 3 executed

**Comment by ilopmar** [comment]
There are some issues with `DeletedElementException` that are fixed now and they will be included in GraalVM 20.3 that will be released in a couple of weeks. I'll try it and I'll see how it goes. Maybe that fixes the issue or maybe we need to change something on Micronaut or open a GraalVM issue.

**Comment by xgaxpp** [comment]
@ilopmar ok, thank you!
